tabs:
  defaultTab: Контакты
  lazy:
      - Контакты
      - Общие
      - Главная страница
      - Цифры
  paneCssClass:
      0: first-tab
      1: second-tab
      2: third-tab
      3: four-tab
  icons:
      Контакты: icon-phone
      Общие: icon-cogs
      Главная страница: icon-home
      Цифры: icon-paw
  fields:
      phone:
          type: text
          label: Телефон
          span: storm
          cssClass: col-md-4
          tab: Контакты
          placeholder: '+79147580525'
      t_email:
          type: email
          label: E-mail
          span: storm
          cssClass: col-md-4
          tab: Контакты
          placeholder: 'example@mail.ru'
      city:
          type: text
          label: Город
          span: storm
          cssClass: col-md-4
          tab: Контакты
          placeholder: 'г. Волгоград'
      address:
          type: text
          label: Адрес
          span: storm
          cssClass: col-md-4
          tab: Контакты
          placeholder: 'ул. Ленина 142'
      post_code:
          type: text
          label: Почтовый индекс
          span: storm
          cssClass: col-md-4
          tab: Контакты
          placeholder: '404100'
      whatsapp:
          type: text
          label: WhatsApp
          span: storm
          cssClass: col-md-4
          tab: Контакты
          placeholder: '79147580525'
      fb:
          type: text
          label: Facebook
          span: storm
          cssClass: col-md-4
          tab: Контакты
          placeholder: 'https://fb.com'
      vk:
          type: text
          label: Вконтакте
          span: storm
          cssClass: col-md-4
          tab: Контакты
          placeholder: https://vk.com
      instagram:
          type: text
          label: Instagram
          span: storm
          cssClass: col-md-4
          tab: Контакты
          placeholder: https://www.instagram.com
      youtube:
          type: text
          label: Youtube
          span: storm
          cssClass: col-md-4
          tab: Контакты
          placeholder: https://www.youtube.com
      map:
          type: textarea
          label: Код карты
          span: storm
          size: large
          cssClass: col-md-12
          tab: Контакты
          placeholder:
      logo_mobile:
          label: Логотип моб.
          type: mediafinder
          mode: image
          imageWidth: 150
          span: storm
          cssClass: col-md-4
          tab: Общие
      logo_full:
          label: Логотип комп.
          type: mediafinder
          mode: image
          imageWidth: 150
          span: storm
          cssClass: col-md-4
          tab: Общие
      site_favicon:
          label: Фавикон
          type: mediafinder
          mode: image
          imageWidth: 150
          span: storm
          cssClass: col-md-4
          tab: Общие
      site_name:
          type: text
          label: Название сайта
          default: LuxEva
          span: storm
          cssClass: col-md-6
          tab: Общие
      site_heading:
          type: text
          label: Заголовок сайта h1
          default: LuxEva
          placeholder: LuxEva
          span: storm
          cssClass: col-md-6
          tab: Общие
      site_description:
          type: textarea
          label: Описание
          default:
          placeholder:
          span: full
          tab: Общие
      site_bg:
          label: Картинка
          type: mediafinder
          mode: image
          imageWidth: 200
          tab: Общие
      site_metrika:
          label: Коды метрик
          type: codeeditor
          size: huge
          language: html
          span: full
          tab: Общие
